name: Publish Helm Chart to GHCR (Prod)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Install yq
        uses: mikefarah/yq@v4

      - name: Read chart version
        id: chart
        run: |
          echo "version=$(yq -r '.version' charts/opencloud/Chart.yaml)" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io \
            --username "${{ github.actor }}" --password-stdin

      - name: Package & Push chart
        run: |
          # Package the chart from repo root (where Chart.yaml lives)
          helm package charts/opencloud --destination .

          # Push to GHCR under opencloud
          TARBALL="opencloud-${{ steps.chart.outputs.version }}.tgz"
          helm push "$TARBALL" oci://ghcr.io/thatfave/opencloud-helm